# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QhMy4XR9J45_i6eeNIANKGMXSkuRB2Ux
"""

import math

def add(num1,num2):

    return num1 + num2

def subtraction(num1,num2):

    return num1 - num2

def division(num1,num2):

    return num1 / num2

def multiplication(num1,num2):

    return num1 * num2

def factorial(num):

    return math.factorial(num)

def exponentiation(num1,num2):

    return math.pow(num1,num2)

def squareRoot(num):

    return math.sqrt(num)

def roundCeil(num):

    return math.ceil(num)

def roundFloor(num):
    
    return math.floor(num)

def run():

  while True:

    choice = input("Please select the action to take\n1-add\n2-subtraction\n3-division\n4-multiplication\n5-factorial\n6-exponentiation\n7-square root\n8-round ceil\n9-round floor\n10-quit\nYour choice: ")

    if choice == "1":
          num1 = float(input("Please enter a number - number 1: "))
          num2 = float(input("Please enter a number - number 2: "))
          a = add(num1,num2)
          print("{} + {} = {}".format(num1,num2,a))

    elif choice == "2":
          num1 = float(input("Please enter a number - number 1: "))
          num2 = float(input("Please enter a number - number 2: "))
          s = subtraction(num1,num2)
          print("{} - {} = {}".format(num1,num2,s))

    elif choice == "3":
          num1 = float(input("Please enter a number - number 1: "))
          num2 = float(input("Please enter a number - number 2: "))
          d =division(num1,num2)
          print("{} / {} = {}".format(num1,num2,d))

    elif choice == "4":
          num1 = float(input("Please enter a number - number 1: "))
          num2 = float(input("Please enter a number - number 2: "))
          m = multiplication(num1,num2)
          print("{} * {} = {}".format(num1,num2,m))

    elif choice == "5":
          num = float(input("Please enter number: "))
          f = factorial(num)
          print("{} ! = {}".format(num,f))

    elif choice == "6":
          num1 = float(input("Please enter a number - number 1: "))
          num2 = float(input("Please enter a number - number 2: "))
          e = exponentiation(num1,num2)
          print("{} ** {} = {}".format(num1,num2,e))

    elif choice == "7":
          num = float(input("Please enter number: "))
          sq = squareRoot(num)
          print("√{} = {}".format(num,sq))

    elif choice == "8":
          num = float(input("Please enter number: "))
          rc = roundCeil(num)
          print("The smallest integer greater than or equal to {}.".format(rc))

    elif choice == "9":
          num = float(input("Please enter number: "))
          rf = roundFloor(num)
          print("The largest integer less than or equal to {}.".format(rf))

    else:
          break


if __name__ == "__main__":
   run()
